// ルートレイアウト: 全ページに共通するコンポーネントを定義
import './globals.css'
import type { Metadata } from 'next'
import Footer from './components/Footer'
import Favicon from '/public/favicon.svg'; //publicフォルダから favicon.svg を読み込む

export const metadata: Metadata = {
  title: 'google clone Next13',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: Favicon.src }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  )
}
